package io.github.turskyi.data.util.exceptions

class NotFoundException : Exception("User not found")